version: '2'
services:
  micronaut-app:
    image: micronaut
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - MICRONAUT_ENVIRONMENTS=prod
      - JDBC_URL=jdbc:mariadb://micronaut-mariadb:3306/micronaut?useLegacyDatetimeCode=false&serverTimezone=UTC
      - JDBC_PASSWORD=password
      - MICRONAUT_SECURITY_OAUTH2_CLIENTS_OIDC_OPENID_ISSUER=http://keycloak:9080/auth/realms/jhipster
      - MICRONAUT_SECURITY_OAUTH2_CLIENTS_OIDC_CLIENT_ID=internal
      - MICRONAUT_SECURITY_OAUTH2_CLIENTS_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
  micronaut-mariadb:
    extends:
      file: mariadb.yml
      service: micronaut-mariadb
  consul:
    extends:
      file: consul.yml
      service: consul

  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader
